CREATE DATABASE temp1;
use temp1;
CREATE TABLE DEPARTMENT(DEPTNO INT PRIMARY KEY,DNAME VARCHAR(40),LOCATION VARCHAR(40));
INSERT DEPARTMENT VALUES(10,'DBA','HYD'),(20,'SAP','MUMBAI'),(30,'HR','PUNE'),(40,'slap','knl');
SELECT*FROM DEPARTMENT;
CREATE TABLE EMPLOYEE(EMPID INT,ENAME VARCHAR(40),SALARY INT,DEPTNO INT,FOREIGN KEY(DEPTNO) REFERENCES  DEPARTMENT(DEPTNO));

INSERT EMPLOYEE VALUES(101,'ADANS',50000,10);
INSERT EMPLOYEE VALUES(102,'PETER',40000,20);
INSERT EMPLOYEE VALUES(103,'JAVES',80000,30);
INSERT EMPLOYEE VALUES(104,'SAP',10000,40);
select*from EMPLOYEE;
DROP TABLE DEPARTMENT
DROP TABLE EMPLOYEE



